package com.example.model;

import java.util.List;

/**
 * Represents a client in a chat system.
 * This interface defines the functionality that any chat client must implement
 * to participate in the chat system.
 *
 * @author Generated by GitHub Copilot
 * @version 1.0
 */
public interface ChatClient {
    public void receiveMessage(Message msg);
    String getUsername();
    String getClientId();
    boolean isActive();
    void notifyClientListUpdated(List<ChatClient> clients);

}
